# Generated by Django 4.2.30 on 2026-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_client_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
