# Generated by Django 4.2.30 on 2026-08-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("IN_PROGRESS", "In Progress"), ("COMPLETED", "Completed")],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
