# Generated by Django 4.2.30 on 2026-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_seed_claim_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimtype",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
