# Generated by Django 4.2.30 on 2026-08-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0004_claimtype_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="claimtype",
            name="bill_required",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="claim",
            name="bill_copy",
            field=models.FileField(
                blank=True, null=True, upload_to="claim_bills/%Y/%m/"
            ),
        ),
    ]
