# Generated by Django 4.2.30 on 2026-08-03 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("claims", "0005_claimtype_bill_required_alter_claim_bill_copy"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="settled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settled_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="settlement_status",
            field=models.CharField(
                choices=[("NOT_SETTLED", "Not Settled"), ("SETTLED", "Settled")],
                default="NOT_SETTLED",
                max_length=15,
            ),
        ),
    ]
