# Generated by Django 4.2.30 on 2026-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0006_claim_project_claim_settled_at_claim_settled_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="amount",
            field=models.PositiveIntegerField(),
        ),
    ]
