# Generated by Django 4.2.30 on 2026-09-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0007_alter_claim_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="claim",
            old_name="from_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="claim",
            name="to_date",
        ),
    ]
