# Generated by Django 4.2.30 on 2026-09-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0008_rename_from_date_claim_date_remove_claim_to_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="claim",
            name="date",
            field=models.DateField(verbose_name="bill date"),
        ),
    ]
