# Generated by Django 4.2.30 on 2026-08-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timesheetentry",
            unique_together=set(),
        ),
    ]
