# Generated by Django 4.2.30 on 2026-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheets", "0002_alter_timesheetentry_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetentry",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="work_mode",
            field=models.CharField(
                choices=[("WFO", "Work From Office"), ("WFH", "Work From Home")],
                default="WFO",
                max_length=3,
            ),
        ),
    ]
